openapi: 3.0.0
info:
  title: 英文添削アプリAPI
  version: 1.0.0

tags:
  - name: Login
    description: ログイン画面
  - name: Logout
    description: ログアウト画面
  - name: UserManagement
    description: 管理者画面・ユーザー編集画面
  - name: Timeline
    description: タイムライン画面
  - name: Comment
    description: 他人の英文にコメントする画面
  - name: Submit
    description: 英文入力画面
  - name: AIModify
    description: AI添削後画面
  - name: Notification
    description: 通知画面
  - name: MyPage
    description: マイページ
  - name: SubmissionDetail
    description: 各投稿の詳細

paths:
  /login:
    post:
      tags:
        - Login
      summary: ログイン
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userid:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: ログイン成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  role:
                    type: string
                    description: "ユーザーの役割（adminまたはuser）"
  
  /logout:
    post:
      tags:
        - Logout
      summary: ログアウト
      responses:
        '200':
          description: ログアウト成功

  /users:
    post:
      tags:
        - UserManagement
      summary: ユーザー作成
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: 作成成功

    get:
      tags:
        - UserManagement
      summary: 全ユーザー取得
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: "ページ番号（1から始まる）"
        - in: query
          name: size
          schema:
            type: integer
            default: 10
          description: "ページサイズ（デフォルトは10)"
      responses:
        '200':
          description: ユーザー情報一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                  - $ref: '#/components/schemas/User'
                  - type: object
                  properties:
                    userid:
                      type: string
                      description: "ユーザーid"
                  required:
                    - userid

  /users/{userid}:
    put:
      tags:
        - UserManagement
      summary: ユーザー更新
      parameters:
        - in: path
          name: userid
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: 更新成功

    delete:
      tags:
        - UserManagement
      summary: ユーザー削除
      parameters:
        - in: path
          name: userid
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 削除成功

  /timeline:
    get:
      tags:
        - Timeline
      summary: タイムライン取得
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: "ページ番号（1から始まる）"
        - in: query
          name: size
          schema:
            type: integer
            default: 10
          description: "ページサイズ（デフォルトは10）"
      responses:
        '200':
          description: 投稿一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nickname:
                      type: string
                    text:
                      type: string
                    date:
                      type: string
                      format: date
                    submissionid:
                      type: string

  /comment/{submissionid}:
    get:
      tags:
        - Comment
      summary: コメント取得
      parameters:
        - in: path
          name: submissionid
          required: true
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: "ページ番号（1から始まる）"
        - in: query
          name: size
          schema:
            type: integer
            default: 10
          description: "ページサイズ（デフォルトは10）"
      responses:
        '200':
          description: コメント内容
          content:
            application/json:
              schema:
                type: object
                properties:
                  nickname:
                    type: string
                  text:
                    type: string
                  corrections:
                    type: array
                    items:
                      $ref: '#/components/schemas/Correction'
                  comments:
                    type: array
                    items:
                      type: object
                      properties:
                        nickname:
                          type: string
                        comment:
                          type: string

    post:
      tags:
        - Comment
      summary: コメント投稿
      parameters:
        - in: path
          name: submissionid
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - comment
              properties:
                comment:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: 投稿成功

  /submit:
    post:
      tags:
        - Submit
      summary: 英文送信（保存なし）
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
      responses:
        '200':
          description: 添削結果
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string
                  corrections:
                    type: array
                    items:
                      $ref: '#/components/schemas/Correction'

  /submit-decide:
    post:
      tags:
        - AIModify
      summary: AI添削後の英文登録
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                corrections:
                  type: array
                  items:
                    $ref: '#/components/schemas/Correction'
      responses:
        '200':
          description: 登録完了

  /notifications:
    get:
      tags:
        - Notification
      summary: 通知取得
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: "ページ番号（1から始まる）"
        - in: query
          name: size
          schema:
            type: integer
            default: 10
          description: "ページサイズ（デフォルトは10）"
      responses:
        '200':
          description: 通知一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    userid:
                      type: string
                    nickname:
                      type: string
                    submissionid:
                      type: string
                    date:
                      type: string
                      format: date-time

  /notification-detail/{userid}/{submissionid}:
    get:
      tags:
        - Notification
      summary: 通知詳細取得
      parameters:
        - in: path
          name: userid
          required: true
          schema:
            type: string
        - in: path
          name: submissionid
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 通知詳細
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string
                  nickname:
                    type: string
                  comments:
                    type: array
                    items:
                      type: object
                      properties:
                        comment:
                          type: string

  /mypage:
    get:
      tags:
        - MyPage
      summary: ユーザーの投稿一覧
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: "ページ番号（1から始まる）"
        - in: query
          name: size
          schema:
            type: integer
            default: 10
          description: "ページサイズ（デフォルトは10）"
      responses:
        '200':
          description: 投稿一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nickname:
                      type: string
                    date:
                      type: string
                      format: date
                    text:
                      type: string
                    submissionid:
                      type: string

  /mypage/{submissionid}:
    delete:
      tags:
        - MyPage
      summary: 投稿削除
      parameters:
        - in: path
          name: submissionid
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 削除完了

  /submission-detail/{submissionid}:
    get:
      tags:
        - SubmissionDetail
      summary: 投稿詳細取得
      parameters:
        - in: path
          name: submissionid
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 投稿詳細
          content:
            application/json:
              schema:
                type: object
                properties:
                  nickname:
                    type: string
                  text:
                    type: string
                  corrections:
                    type: array
                    items:
                      $ref: '#/components/schemas/Correction'
                  comments:
                    type: array
                    items:
                      type: object
                      properties:
                        nickname:
                          type: string
                        comment:
                          type: string


components:
  schemas:
    User:
      type: object
      properties:
        nickname:
          type: string
        password:
          type: string
        name:
          type: string
        mailaddress:
          type: string
        role:
          type: string
          description: "ユーザーの役割（adminまたはuser）"

    Correction:
      type: object
      properties:
        original:
          type: string
        corrected:
          type: string
        reason:
          type: string
